### ISSUE TITLE
能否用加入muon

### ISSUE THREAD

**Issue by iamiceice** [duolabmeng6/GoEasyDesigner#2]
能否使用muon,链接：https://github.com/ImVexed/muon，与wails和electron类似，不过已经4年没更新了。

**Comment by duolabmeng6** [comment]
没有精力做这些适配哦 下一步会是 wailsV3的适配 还有 electronjs 如果你需要 muon 可以自行拉取代码修改 前端代码是可以独立运行的与 wails无关
