### ISSUE TITLE
建议删掉代码编辑器

### ISSUE THREAD

**Issue by pkuntik** [duolabmeng6/GoEasyDesigner#5]
建议删掉代码编辑器，goland已经做的很好了，建议封装成goland插件形式，给go项目做一个窗口设计器。

**Comment by duolabmeng6** [comment]
https://github.com/duolabmeng6/GoEasyDesigner/assets/59047063/b59b6134-baf8-430b-a269-62cf1d9e97d3

这里可以查看效果

**Comment by duolabmeng6** [comment]
代码编辑器起到一个承上启下的作用
后期会把项目环境全部带上 可以做到无ide的情况下做轻量的开发和编译
设计器也会有支持库函数的提示和帮助 虽然未完成开发
但我们是拥有goefun这样的中文函数库目前是可以直接使用的

**Comment by duolabmeng6** [comment]
> 感觉能用go语言直接开发更好，无论从安全性、性能、开发效率上来讲go都比js更好点。而且现在有挺多人重度依赖github copilot，双击组件跳转到go语言对应的事件代码那么开发起来就爽极了。

双击组件跳转到go语言对应的事件代码那么开发起来就爽极了 这个一直都有的 按照教程安装插件就行
