### ISSUE TITLE
建议构建加一个搞成可以直接webpack打包好的src

### ISSUE THREAD

**Issue by fanxiangyu399** [duolabmeng6/GoEasyDesigner#8]

**Comment by duolabmeng6** [comment]
不知道你说得是意思喔

**Comment by fanxiangyu399** [comment]
就是，目前点击构建后是生成exe桌面窗口程序的，就是希望他生成后可以直接拿去对接其它语言的那种，就像一个正常的项目拿去用webpack打包后直接部署，可以直接部署到服务器的那种形式，相当于不完全服务于易语言

**Comment by duolabmeng6** [comment]
这是个vite的vue项目，你可以复制出来单独部署啊 npm run dev呀... 这个多学习一下就好了
